version: '3.8'

services:
  # 1. DATABASE
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: hula_user
      POSTGRES_PASSWORD: hula_password
      POSTGRES_DB: hula_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. BACKEND
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: hula_user
      DB_PASSWORD: hula_password
      DB_DATABASE: hula_db

  # 3. FRONTEND (Sua lai volume)
  frontend:
    build: ./frontend
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # <--- DONG QUAN TRONG: GIU LAI THU VIEN
    environment:
      - VITE_API_URL=http://35.235.245.130:3000
    depends_on:
      - app

volumes:
  postgres_data:
