version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hula_db
    restart: always
    environment:
      POSTGRES_USER: hula_user
      POSTGRES_PASSWORD: hula_password
      POSTGRES_DB: hula_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hula_user -d hula_db" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - default

  app:
    build:
      context: .
      target: development # Use Dev Stage (No Build)
    container_name: hula_app
    restart: always
    command: npm run start:dev # Chạy chế độ Dev (Hot Reload)
    # ports:
    #   - "3000:3000" # Disable port mapping (Use Proxy instead)
    expose:
      - "3000" # Expose to internal network only
    environment:
      - DB_HOST=hula_db
      - DB_PORT=5432
      - DB_USERNAME=hula_user
      - DB_PASSWORD=hula_password
      - DB_DATABASE=hula_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - proxy_net
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - ./tsconfig.json:/app/tsconfig.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production # Use Production Stage (Nginx)
    container_name: hula_frontend
    restart: always
    expose:
      - "80" # Nginx default port
    depends_on:
      - app
    networks:
      - default
      - proxy_net

volumes:
  postgres_data:


networks:
  default:
    driver: bridge
  proxy_net:
    external: true # Join the Nginx Proxy Manager network
