-- Auto-generated seed file for 360-degree review questions
INSERT INTO review_question (content, category, type, created_at, updated_at) VALUES
('Chủ động: Chủ động tìm kiếm giải pháp trước khi nhờ sự trợ giúp.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Chủ động: Sẵn sàng nhận thêm trách nhiệm khi đội ngũ cần.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Chủ động: Tự giác theo dõi và cập nhật tiến độ công việc không cần nhắc nhở.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Chủ động: Đề xuất ý tưởng mới thay vì chỉ làm theo lối mòn.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Chủ động: Tự tìm hiểu kiến thức mới để phục vụ dự án Renew Hula.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Tốc độ: Phản hồi tin nhắn/email công việc nội bộ trong thời gian quy định.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Tốc độ: Xử lý các phát sinh đột xuất một cách nhanh chóng, linh hoạt.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Tốc độ: Đảm bảo tốc độ thực thi chiến dịch mà vẫn giữ được chất lượng.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Tốc độ: Ra quyết định hành động nhanh trong phạm vi quyền hạn của mình.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Tốc độ: Hoàn thành các báo cáo/task đột xuất đúng hạn.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Trách nhiệm: Chịu trách nhiệm 100% về kết quả công việc của cá nhân.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Trách nhiệm: Không đổ lỗi cho hoàn cảnh hoặc đồng nghiệp khi xảy ra sự cố.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Trách nhiệm: Theo đuổi công việc đến cùng cho dù gặp nhiều trở ngại.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Trách nhiệm: Thừa nhận sai sót và chủ động đưa ra phương án khắc phục.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Trách nhiệm: Bảo vệ tài sản, uy tín và bảo mật thông tin của Hula.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Đổi mới: Tìm kiếm các công cụ AI/tự động hóa để tối ưu hiệu suất công việc.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Đổi mới: Thử nghiệm các cách làm marketing/vận hành mới đem lại hiệu quả cao hơn.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Đổi mới: Tiếp nhận các đóng góp đổi mới từ đồng nghiệp với thái độ cởi mở.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Đổi mới: Đóng góp sáng kiến cải tiến giao diện hoặc quy trình e-commerce.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Đổi mới: Thách thức các quy trình cũ đã lỗi thời trong vận hành.', 'Văn hóa cốt lõi', 'RATING', NOW(), NOW()),
('Trung thực: Minh bạch trong việc báo cáo số liệu dữ liệu (Doanh thu/Chi phí).', 'Đạo đức làm việc', 'RATING', NOW(), NOW()),
('Trung thực: Đánh giá đúng năng lực và hạn chế của bản thân.', 'Đạo đức làm việc', 'RATING', NOW(), NOW()),
('Trung thực: Thẳng thắn góp ý xây dựng mang tính chất giúp đồng nghiệp tiến bộ.', 'Đạo đức làm việc', 'RATING', NOW(), NOW()),
('Tôn trọng: Tôn trọng sự khác biệt về quan điểm trong các cuộc họp Core Team.', 'Đạo đức làm việc', 'RATING', NOW(), NOW()),
('Tôn trọng: Lắng nghe trọn vẹn ý kiến của người khác trước khi phản biện.', 'Đạo đức làm việc', 'RATING', NOW(), NOW()),
('Tôn trọng: Ứng xử lịch sự, chuyên nghiệp với đồng nghiệp và đối tác.', 'Đạo đức làm việc', 'RATING', NOW(), NOW()),
('Cam kết: Đạt được các cam kết cá nhân đã thỏa thuận đầu tháng.', 'Đạo đức làm việc', 'RATING', NOW(), NOW()),
('Cam kết: Tuân thủ giờ giấc và quy chế làm việc chung của startup.', 'Đạo đức làm việc', 'RATING', NOW(), NOW()),
('Cam kết: Đồng hành cùng đội ngũ trong các giai đoạn cao điểm của dự án.', 'Đạo đức làm việc', 'RATING', NOW(), NOW()),
('Đồng lòng: Sẵn sàng hỗ trợ làm các công việc ngoài JD khi tình huống yêu cầu.', 'Tinh thần Startup', 'RATING', NOW(), NOW()),
('Tối ưu chi phí: Ý thức tiết kiệm ngân sách, tài nguyên cho công ty.', 'Tinh thần Startup', 'RATING', NOW(), NOW()),
('Thích ứng: Giữ năng lượng tích cực trước các thay đổi đột ngột về chiến lược.', 'Tinh thần Startup', 'RATING', NOW(), NOW()),
('Lan tỏa: Thể hiện niềm tự hào về thương hiệu Hula ra bên ngoài.', 'Tinh thần Startup', 'RATING', NOW(), NOW()),
('Rõ ràng: Truyền đạt thông tin ngắn gọn, dễ hiểu, đi thẳng vào trọng tâm.', 'Giao tiếp nội bộ', 'RATING', NOW(), NOW()),
('Lắng nghe: Hiểu đúng và đủ các chỉ thị, yêu cầu từ cấp trên.', 'Giao tiếp nội bộ', 'RATING', NOW(), NOW()),
('Phản hồi: Cung cấp feedback kịp thời sau khi nhận được sản phẩm từ team khác.', 'Giao tiếp nội bộ', 'RATING', NOW(), NOW()),
('Mục tiêu chung: Hiểu rõ tầm nhìn cốt lõi của chiến dịch Renew Hula hiện tại.', 'Thấu hiểu chung', 'RATING', NOW(), NOW()),
('Vai trò: Biết rõ công việc của mình đóng góp thế nào vào doanh thu chung.', 'Thấu hiểu chung', 'RATING', NOW(), NOW()),
('Khách hàng: Luôn đặt trải nghiệm của khách hàng Hula lên hàng đầu.', 'Thấu hiểu chung', 'RATING', NOW(), NOW()),
('Điểm mạnh: Nhận diện rõ điểm mạnh nhất đóng góp cho đội ngũ trong tháng.', 'Tự nhận thức', 'RATING', NOW(), NOW()),
('Hoàn thành KPI: Đạt hoặc vượt mức các chỉ tiêu KPI định lượng đề ra.', 'Hiệu suất', 'RATING', NOW(), NOW()),
('Tiến độ: Hoàn thành 100% các milestone quan trọng đúng hạn.', 'Hiệu suất', 'RATING', NOW(), NOW()),
('Chất lượng: Sản phẩm đầu ra đáp ứng tiêu chuẩn thẩm mỹ/kỹ thuật của Hula.', 'Hiệu suất', 'RATING', NOW(), NOW()),
('Khối lượng: Xử lý được khối lượng công việc lớn mà không bị quá tải.', 'Hiệu suất', 'RATING', NOW(), NOW()),
('Độ chính xác: Hạn chế tối đa các sai sót ngớ ngẩn do thiếu cẩn thận.', 'Hiệu suất', 'RATING', NOW(), NOW()),
('Sắp xếp: Biết cách phân loại công việc theo thứ tự ưu tiên (Quan trọng/Khẩn cấp).', 'Quản lý công việc', 'RATING', NOW(), NOW()),
('Lập kế hoạch: Xây dựng kế hoạch làm việc tuần/tháng chi tiết, khả thi.', 'Quản lý công việc', 'RATING', NOW(), NOW()),
('Tối ưu thời gian: Sử dụng thời gian làm việc hiệu quả, giảm thiểu thời gian chết.', 'Quản lý công việc', 'RATING', NOW(), NOW()),
('Báo cáo: Thực hiện báo cáo tiến độ định kỳ đầy đủ, trực quan.', 'Quản lý công việc', 'RATING', NOW(), NOW()),
('Lưu trữ: Quản lý và lưu trữ dữ liệu dự án khoa học trên driver chung.', 'Quản lý công việc', 'RATING', NOW(), NOW()),
('Phát hiện: Nhận diện sớm các rủi ro, sự cố trước khi chúng bùng phát.', 'Giải quyết vấn đề', 'RATING', NOW(), NOW()),
('Phân tích: Tìm ra nguyên nhân gốc rễ (Root cause) của vấn đề thay vì xử lý ngọn.', 'Giải quyết vấn đề', 'RATING', NOW(), NOW()),
('Độc lập: Có khả năng tự đưa ra các giải pháp tình huống hiệu quả.', 'Giải quyết vấn đề', 'RATING', NOW(), NOW()),
('Quyết đoán: Đưa ra lựa chọn giải pháp dứt khoát trong tình huống khẩn cấp.', 'Giải quyết vấn đề', 'RATING', NOW(), NOW()),
('Đúc rút kinh nghiệm: Rút ra bài học cụ thể sau mỗi lần thất bại hoặc xảy ra sự cố.', 'Giải quyết vấn đề', 'RATING', NOW(), NOW()),
('Sử dụng công cụ: Thành thạo các công cụ làm việc được giao (M365, Shopee Uni,...).', 'Kỹ năng kỹ thuật', 'RATING', NOW(), NOW()),
('Quy trình: Tuân thủ nghiêm ngặt các quy trình vận hành tiêu chuẩn (SOP).', 'Kỹ năng kỹ thuật', 'RATING', NOW(), NOW()),
('Dữ liệu: Biết cách đọc hiểu và phân tích các chỉ số dữ liệu cơ bản của công việc.', 'Kỹ năng kỹ thuật', 'RATING', NOW(), NOW()),
('Cải tiến năng suất: Đưa ra các giải pháp giúp giảm thời gian xử lý một task cụ thể.', 'Tư duy tối ưu', 'RATING', NOW(), NOW()),
('Giảm chi phí: Đóng góp ý kiến loại bỏ các bước trung gian gây lãng phí.', 'Tư duy tối ưu', 'RATING', NOW(), NOW()),
('Chịu áp lực: Duy trì được hiệu suất ổn định ngay cả trong mùa cao điểm.', 'Độ bền bỉ', 'RATING', NOW(), NOW()),
('Kiên trì: Không nản lòng khi các chỉ số chuyển đổi/vận hành chưa đạt kỳ vọng.', 'Độ bền bỉ', 'RATING', NOW(), NOW()),
('Giữ bình tĩnh: Kiểm soát tốt cảm xúc cá nhân khi gặp khách hàng khó tính hoặc sự cố.', 'Độ bền bỉ', 'RATING', NOW(), NOW()),
('Nhạy bén thị trường: Cập nhật nhanh các xu hướng mới của đối thủ cạnh tranh trên thị trường.', 'Tư duy thương mại', 'RATING', NOW(), NOW()),
('Tối ưu phễu: Hiểu rõ hành vi khách hàng để tối ưu điểm chạm trong công việc.', 'Tư duy thương mại', 'RATING', NOW(), NOW()),
('Tập trung: Tránh bị xao lãng bởi các yếu tố bên ngoài trong giờ làm việc.', 'Hiệu quả làm việc', 'RATING', NOW(), NOW()),
('Tự quản lý: Làm việc hiệu quả ngay cả khi không có sự giám sát trực tiếp.', 'Hiệu quả làm việc', 'RATING', NOW(), NOW()),
('Dự phòng: Luôn có phương án B dự phòng cho các công việc quan trọng.', 'Quản lý rủi ro', 'RATING', NOW(), NOW()),
('Bảo mật: Ý thức cao về việc bảo mật thông tin tài khoản doanh nghiệp.', 'Quản lý rủi ro', 'RATING', NOW(), NOW()),
('Bàn giao: Bàn giao công việc rõ ràng, đầy đủ thông tin cho người kế nhiệm.', 'Phối hợp tác chiến', 'RATING', NOW(), NOW()),
('Tự nhận xét: Đánh giá chính xác mức độ đóng góp của mình so với các đồng nghiệp.', 'Đánh giá năng lực', 'RATING', NOW(), NOW()),
('Đón nhận góp ý: Tiếp thu các ý kiến phê bình từ cấp trên một cách tích cực.', 'Đánh giá năng lực', 'RATING', NOW(), NOW()),
('Học hỏi: Tận dụng thời gian rảnh để tự nâng cao năng lực chuyên môn.', 'Phát triển bản thân', 'RATING', NOW(), NOW()),
('Thử thách: Chủ động nhận các công việc mới khó hơn để bứt phá giới hạn.', 'Phát triển bản thân', 'RATING', NOW(), NOW()),
('Chuẩn bị: Chuẩn bị đầy đủ tài liệu trước khi bước vào các buổi họp tháng.', 'Hiệu quả họp', 'RATING', NOW(), NOW()),
('Đóng góp: Phát biểu ý kiến đóng góp có giá trị, xây dựng trong cuộc họp.', 'Hiệu quả họp', 'RATING', NOW(), NOW()),
('Ghi nhớ: Thực thi đúng và đủ các action plan sau cuộc họp.', 'Hiệu quả họp', 'RATING', NOW(), NOW()),
('Liên kết: Nhìn nhận công việc của mình trong bức tranh tổng thể của Hula.', 'Tư duy hệ thống', 'RATING', NOW(), NOW()),
('Tiêu chuẩn hóa: Thể chế hóa các cách làm tốt thành quy trình để chuyển giao.', 'Tư duy hệ thống', 'RATING', NOW(), NOW()),
('Tự hào: Hài lòng với tổng giá trị mình đã tạo ra cho Hula trong tháng qua.', 'Hiệu suất tổng thể', 'RATING', NOW(), NOW()),
('Đồng bộ thông tin: Đội Marketing thông báo sớm về các chiến dịch khuyến mãi cho Vận hành.', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Chuẩn bị hàng hóa: Vận hành chuẩn bị đủ số lượng tồn kho theo dự báo (forecast) của Marketing.', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Đồng bộ Shopee: Marketing và Vận hành thống nhất được giá bán, flash sale trên Shopee.', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Phản hồi tồn kho: Vận hành cập nhật kịp thời trạng thái kho hàng để Marketing điều chỉnh bài chạy Ads.', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Tốc độ xử lý đơn: Vận hành đóng gói và giao hàng kịp thời khi Marketing đẩy mạnh campaign.', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Giao tiếp chéo: Việc trao đổi công việc giữa 2 team diễn ra thuận lợi, không có rào cản.', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Chia sẻ dữ liệu: Hai bên chủ động chia sẻ dữ liệu (Dữ liệu Ads vs Dữ liệu Đơn hàng thực tế).', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Xử lý khủng hoảng: Phối hợp nhịp nhàng khi có sự cố đơn hàng hoặc feedback xấu từ khách hàng.', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Thấu hiểu JD: Marketing hiểu khó khăn của Vận hành và ngược lại.', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Đạt mục tiêu chung: Cả hai team đặt mục tiêu tăng trưởng tối ưu của Hula lên trên lợi ích phòng ban.', 'Phối hợp Mar-Ops', 'RATING', NOW(), NOW()),
('Tuân thủ SOP: Cả hai team tuân thủ đúng quy trình bàn giao công việc đã quy định.', 'Quy trình phối hợp', 'RATING', NOW(), NOW()),
('Đúng hạn (SLA): Thời gian phản hồi yêu cầu giữa 2 phòng ban đáp ứng đúng cam kết SLA.', 'Quy trình phối hợp', 'RATING', NOW(), NOW()),
('Sự rõ ràng: Yêu cầu (Brief) từ Marketing gửi sang Vận hành rõ ràng, không gây hiểu lầm.', 'Quy trình phối hợp', 'RATING', NOW(), NOW()),
('Điểm chạm công nghệ: Hệ thống CRM/Quản lý đơn hàng giữa Marketing và Vận hành hoạt động đồng bộ.', 'Quy trình phối hợp', 'RATING', NOW(), NOW()),
('Cải tiến quy trình: Hai bên thường xuyên ngồi lại để tối ưu hóa quy trình đóng gói - giao hàng.', 'Quy trình phối hợp', 'RATING', NOW(), NOW()),
('Hỗ trợ: Sẵn sàng tăng ca cùng nhau khi có các đợt siêu sale (9/9, 11/11, v.v.).', 'Thái độ hợp tác', 'RATING', NOW(), NOW()),
('Tích cực: Thảo luận tìm giải pháp thay vì đổ lỗi khi đơn hàng bị hoàn/hủy tăng cao.', 'Thái độ hợp tác', 'RATING', NOW(), NOW()),
('Tin tưởng: Tin tưởng vào năng lực và chuyên môn của nhân sự phòng ban đối diện.', 'Thái độ hợp tác', 'RATING', NOW(), NOW()),
('Ghi nhận: Chủ động khen ngợi, ghi nhận nỗ lực của team bạn khi chiến dịch thành công.', 'Thái độ hợp tác', 'RATING', NOW(), NOW()),
('Lắng nghe phản hồi: Sẵn sàng sửa đổi cách làm việc khi nhận được góp ý từ team bạn.', 'Thái độ hợp tác', 'RATING', NOW(), NOW()),
('Nhất quán thương hiệu: Vận hành đóng gói đúng quy chuẩn đóng gói cao cấp của Branding yêu cầu.', 'Quản lý hình ảnh', 'RATING', NOW(), NOW()),
('Quà tặng đi kèm: Phối hợp chuẩn bị chỉn chu các sản phẩm quà tặng (gift kèm đơn) cho khách hàng.', 'Quản lý hình ảnh', 'RATING', NOW(), NOW()),
('Thẻ cảm ơn: Đảm bảo 100% đơn hàng đi kèm thiệp cảm ơn/hướng dẫn sử dụng chuẩn chỉnh.', 'Quản lý hình ảnh', 'RATING', NOW(), NOW()),
('Giảm tỷ lệ hủy: Phối hợp gọi điện xác nhận đơn/chăm sóc để giảm tỷ lệ bom hàng.', 'Tối ưu vận hành', 'RATING', NOW(), NOW()),
('Xử lý hàng lỗi: Quy trình thu hồi, đổi trả sản phẩm lỗi cho khách được xử lý mượt mà.', 'Tối ưu vận hành', 'RATING', NOW(), NOW()),
('Đồng bộ kênh: Đồng bộ thông tin khuyến mãi offline (nếu có) và online nhất quán.', 'Tối ưu vận hành', 'RATING', NOW(), NOW()),
('Tối ưu chi phí quà: Thống nhất được chi phí sản xuất quà tặng kèm hợp lý với ngân sách Marketing.', 'Chiến lược chung', 'RATING', NOW(), NOW()),
('Thử nghiệm mẫu mới: Vận hành chuẩn bị nhanh các mẫu thử mới để Marketing làm tư liệu quay chụp.', 'Chiến lược chung', 'RATING', NOW(), NOW()),
('Tự giải quyết: Nhân sự 2 bên tự giải quyết được các bất đồng nhỏ mà không cần escalate lên CCO/CEO.', 'Kỹ năng giải quyết', 'RATING', NOW(), NOW()),
('Điểm số phối hợp: Đánh giá tổng thể mức độ phối hợp Mar-Ops tháng này tốt hơn tháng trước.', 'Đánh giá chung', 'RATING', NOW(), NOW()),
('Kênh khẩn cấp: Có kênh hotline/nhóm chat khẩn cấp hoạt động hiệu quả khi sập sàn/lỗi giá.', 'Giao tiếp linh hoạt', 'RATING', NOW(), NOW()),
('Cảnh báo cháy hàng: Vận hành cảnh báo sớm các mã hàng sắp hết để Marketing tắt Ads kịp thời.', 'Đồng bộ tồn kho', 'RATING', NOW(), NOW()),
('Đổi mới bao bì: Marketing lắng nghe phản hồi của Vận hành về độ bền của bao bì khi vận chuyển xa.', 'Tối ưu đóng gói', 'RATING', NOW(), NOW()),
('Gợi ý sản phẩm: Vận hành chia sẻ xu hướng đóng gói độc đáo của đối thủ để Marketing học hỏi.', 'Theo dõi đối thủ', 'RATING', NOW(), NOW()),
('Chi phí vận chuyển: Phối hợp tìm kiếm các đơn vị vận chuyển tối ưu để giảm phí ship cho khách.', 'Quản lý chi phí', 'RATING', NOW(), NOW()),
('Unboxing experience: Hai bên cùng hướng tới việc tạo ra trải nghiệm bóc hộp xuất sắc cho khách hàng.', 'Trải nghiệm bóc hộp', 'RATING', NOW(), NOW()),
('Hỗ trợ nhân lực: Đội Marketing sẵn sàng hỗ trợ dán tem/nhãn khi kho bị quá tải đơn hàng.', 'Đồng bộ nhân sự', 'RATING', NOW(), NOW()),
('Hiểu công việc: Nhân sự Marketing hiểu quy trình đóng gói và ngược lại thông qua các buổi share.', 'Đào tạo chéo', 'RATING', NOW(), NOW()),
('Thống nhất data: Hai phòng ban sử dụng chung một nguồn dữ liệu làm chuẩn, không bị lệch số.', 'Thống nhất chỉ số', 'RATING', NOW(), NOW()),
('Sáng kiến chung: Có ít nhất 1 sáng kiến chung giữa Mar &amp; Ops được áp dụng thành công tháng này.', 'Đóng góp sáng kiến', 'RATING', NOW(), NOW()),
('Tầm nhìn định hướng: Đưa ra định hướng chiến lược rõ ràng cho dự án Renew Hula.', 'Lãnh đạo', 'RATING', NOW(), NOW()),
('Truyền cảm hứng: Tạo động lực mạnh mẽ và duy trì năng lượng tích cực cho đội ngũ.', 'Lãnh đạo', 'RATING', NOW(), NOW()),
('Gương mẫu: Đi đầu trong việc thực hiện các giá trị cốt lõi và văn hóa của Hula.', 'Lãnh đạo', 'RATING', NOW(), NOW()),
('Đáng tin cậy: Nhất quán giữa lời nói và hành động thực tế.', 'Lãnh đạo', 'RATING', NOW(), NOW()),
('Bảo vệ đội ngũ: Sẵn sàng đứng ra chịu trách nhiệm cuối cùng trước các thất bại của team.', 'Lãnh đạo', 'RATING', NOW(), NOW()),
('Thiết lập mục tiêu: Đặt ra các mục tiêu OKR/KPI hàng tháng thách thức nhưng khả thi.', 'Chiến lược', 'RATING', NOW(), NOW()),
('Nhạy bén kinh doanh: Nhận diện nhanh các cơ hội thị trường e-commerce mới để áp dụng cho Hula.', 'Chiến lược', 'RATING', NOW(), NOW()),
('Quản trị rủi ro: Có các kịch bản ứng phó rủi ro tốt về mặt dòng tiền và nhân sự.', 'Chiến lược', 'RATING', NOW(), NOW()),
('Tập trung chiến lược: Kiên định với các mục tiêu cốt lõi, không bị phân tán bởi cơ hội ngắn hạn.', 'Chiến lược', 'RATING', NOW(), NOW()),
('Tối ưu cấu trúc: Sắp xếp bộ máy nhân sự tinh gọn, đúng người đúng việc.', 'Chiến lược', 'RATING', NOW(), NOW()),
('Phân công công việc: Giao việc rõ ràng, đúng năng lực và phạm vi trách nhiệm của từng nhân sự.', 'Quản lý con người', 'RATING', NOW(), NOW()),
('Trao quyền: Tin tưởng, tạo không gian chủ động cho cấp dưới tự quyết trong thẩm quyền.', 'Quản lý con người', 'RATING', NOW(), NOW()),
('Hướng dẫn (Coaching): Dành thời gian kèm cặp, chia sẻ kinh nghiệm giúp nhân viên phát triển chuyên môn.', 'Quản lý con người', 'RATING', NOW(), NOW()),
('Đánh giá công bằng: Nhìn nhận hiệu suất đóng góp của nhân viên khách quan, không định kiến.', 'Quản lý con người', 'RATING', NOW(), NOW()),
('Giải quyết xung đột: Xử lý các mâu thuẫn nội bộ (đặc biệt giữa Mar &amp; Ops) thấu tình đạt lý.', 'Quản lý con người', 'RATING', NOW(), NOW()),
('Dựa trên dữ liệu: Ra quyết định dựa trên số liệu thực tế thay vì cảm tính cá nhân.', 'Ra quyết định', 'RATING', NOW(), NOW()),
('Tốc độ quyết định: Đưa ra các quyết định điều hành nhanh chóng, không ngâm duyệt làm chậm tiến độ.', 'Ra quyết định', 'RATING', NOW(), NOW()),
('Lắng nghe ý kiến: Tham khảo ý kiến phản hồi của các thành viên Core Team trước khi chốt phương án.', 'Ra quyết định', 'RATING', NOW(), NOW()),
('Tính thực tế: Các quyết định đưa ra phù hợp với nguồn lực thực tế của startup.', 'Ra quyết định', 'RATING', NOW(), NOW()),
('Đổi mới giải pháp: Linh hoạt thay đổi quyết định cũ khi bối cảnh thị trường thay đổi đột ngột.', 'Ra quyết định', 'RATING', NOW(), NOW()),
('Phân bổ ngân sách: Chi tiêu ngân sách marketing và vận hành hợp lý, tối ưu ROI.', 'Quản lý tài nguyên', 'RATING', NOW(), NOW()),
('Tận dụng công nghệ: Thúc đẩy việc ứng dụng công nghệ để giải phóng sức lao động cho team.', 'Quản lý tài nguyên', 'RATING', NOW(), NOW()),
('Sắp xếp thời gian: Tổ chức các cuộc họp Core Team ngắn gọn, đi thẳng vào giải pháp.', 'Quản lý tài nguyên', 'RATING', NOW(), NOW()),
('Lắng nghe tâm tư: Thấu hiểu các khó khăn về đời sống, phúc lợi (salary/insurance) của nhân viên.', 'Quan tâm nhân sự', 'RATING', NOW(), NOW()),
('Ghi nhận kịp thời: Khen thưởng xứng đáng cho những nhân sự có đóng góp đột phá.', 'Quan tâm nhân sự', 'RATING', NOW(), NOW()),
('Xây dựng môi trường: Tạo dựng môi trường làm việc an toàn, minh bạch, không toxic.', 'Quan tâm nhân sự', 'RATING', NOW(), NOW()),
('Minh bạch thông tin: Cập nhật tình hình &quot;sức khỏe&quot; của công ty đầy đủ cho Core Team.', 'Giao tiếp cấp quản lý', 'RATING', NOW(), NOW()),
('Phản hồi hiệu suất: Có các buổi 1-1 chất lượng để chỉ ra điểm cần cải thiện cho cấp dưới.', 'Giao tiếp cấp quản lý', 'RATING', NOW(), NOW()),
('Giữ gìn bản sắc: Kiên trì rèn luyện thói quen làm việc tốc độ và trách nhiệm cho tổ chức.', 'Phát triển văn hóa', 'RATING', NOW(), NOW()),
('Sẵn sàng thay đổi: Chấp nhận các góp ý ngược (upward feedback) từ nhân viên để tự sửa đổi.', 'Tinh thần cầu tiến', 'RATING', NOW(), NOW()),
('Thúc đẩy doanh số: Đưa ra các chiến lược chuyển đổi đột phá trên sàn Shopee.', 'Năng lực CCO', 'RATING', NOW(), NOW()),
('Phát triển kênh: Tìm kiếm và mở rộng thành công các kênh phân phối mới tiềm năng.', 'Năng lực CCO', 'RATING', NOW(), NOW()),
('Quản lý đối tác: Duy trì mối quan hệ tốt đẹp với các đối tác chiến lược và nhà cung cấp.', 'Năng lực CCO', 'RATING', NOW(), NOW()),
('Dự báo thị trường: Dự báo doanh số sát với thực tế, độ lệch thấp dưới mức quy định.', 'Năng lực CCO', 'RATING', NOW(), NOW()),
('Quản trị dòng tiền: Đảm bảo dòng tiền vận hành của startup luôn ở mức an toàn.', 'Năng lực CEO', 'RATING', NOW(), NOW()),
('Kết nối Core Team: Giữ vững sự đồng thuận và đoàn kết tuyệt đối trong hàng ngũ lãnh đạo.', 'Năng lực CEO', 'RATING', NOW(), NOW()),
('Phát triển đối ngoại: Đại diện xuất sắc cho hình ảnh thương hiệu Hula trước công chúng.', 'Năng lực CEO', 'RATING', NOW(), NOW()),
('Định hướng sản phẩm: Đưa ra định hướng cải tiến bao bì, chất lượng sản phẩm xuất sắc.', 'Năng lực CEO', 'RATING', NOW(), NOW()),
('Vững tay chèo: Giữ sự bình tĩnh, kiên định dẫn dắt team vượt qua khủng hoảng.', 'Khả năng chịu đựng', 'RATING', NOW(), NOW()),
('Đáng tin cậy: Tổng thể, tôi hoàn toàn tin tưởng vào sự dẫn dắt của vị quản lý này.', 'Điểm số chung', 'RATING', NOW(), NOW()),
('Thành tựu cá nhân: Ba thành công lớn nhất bạn đạt được trong tháng qua là gì?', 'Định tính', 'RATING', NOW(), NOW()),
('Bài học thất bại: Một công việc bạn làm chưa tốt trong tháng và bài học rút ra là gì?', 'Định tính', 'RATING', NOW(), NOW()),
('Điểm nghẽn Mar-Ops: Ghi lại 1 tình huống cụ thể mà sự phối hợp giữa Mar và Ops bị lỗi trong tháng?', 'Định tính', 'RATING', NOW(), NOW()),
('Đề xuất giải pháp: Giải pháp của bạn để tình huống lỗi phối hợp trên không tái diễn là gì?', 'Định tính', 'RATING', NOW(), NOW()),
('Công cụ làm việc: Công cụ hoặc quy trình nào hiện tại đang làm chậm tốc độ làm việc của bạn?', 'Định tính', 'RATING', NOW(), NOW()),
('Ý tưởng Shopee: Bạn có đề xuất gì để tăng tỷ lệ click hoặc tỷ lệ chuyển đổi đơn hàng Shopee?', 'Định tính', 'RATING', NOW(), NOW()),
('Ý tưởng sản phẩm: Ý tưởng cải tiến bao bì hoặc trải nghiệm đập hộp của Hula là gì?', 'Định tính', 'RATING', NOW(), NOW()),
('Hỗ trợ cấp trên: Bạn cần quản lý trực tiếp hỗ trợ giải quyết vấn đề gì trong tháng tới?', 'Định tính', 'RATING', NOW(), NOW()),
('Ghi nhận đồng nghiệp: Hãy nêu tên 1 đồng nghiệp đã hỗ trợ bạn xuất sắc nhất trong tháng và lý do?', 'Định tính', 'RATING', NOW(), NOW()),
('Sáng kiến chi phí: Sáng kiến nào giúp Hula tiết kiệm được chi phí vận hành/marketing trong tháng tới?', 'Định tính', 'RATING', NOW(), NOW()),
('Đóng góp văn hóa: Bạn đã làm gì để lan tỏa văn hóa &quot;Tốc độ và Trách nhiệm&quot; đến đội ngũ?', 'Định tính', 'RATING', NOW(), NOW()),
('Nhu cầu đào tạo: Kỹ năng chuyên môn nào bạn muốn được công ty đào tạo thêm trong thời gian tới?', 'Định tính', 'RATING', NOW(), NOW()),
('Đề xuất chế độ: Đề xuất nào về môi trường làm việc giúp tăng năng suất của bạn?', 'Định tính', 'RATING', NOW(), NOW()),
('Nhận xét về CEO: Góp ý thẳng thắn giúp CEO điều hành hiệu quả hơn trong tháng tới?', 'Định tính', 'RATING', NOW(), NOW()),
('Nhận xét về CCO: Góp ý thẳng thắn giúp CCO đẩy mạnh hiệu quả thương mại hơn?', 'Định tính', 'RATING', NOW(), NOW()),
('Mục tiêu tháng tới: Mục tiêu quan trọng nhất (Focus target) bạn cam kết đạt được vào tháng sau?', 'Định tính', 'RATING', NOW(), NOW()),
('Ý kiến khác: Bất kỳ tâm tư, nguyện vọng nào khác bạn muốn chia sẻ bảo mật với Core Team?', 'Định tính', 'RATING', NOW(), NOW()),
('Phối hợp: Nhân sự được đánh giá có chủ động hỗ trợ bạn khi bạn quá tải không?', 'Đánh giá đồng nghiệp', 'RATING', NOW(), NOW()),
('Thái độ: Nhân sự được đánh giá có lắng nghe các góc nhìn chuyên môn của bạn không?', 'Đánh giá đồng nghiệp', 'RATING', NOW(), NOW()),
('Uy tín: Bạn có hoàn toàn yên tâm khi giao việc/phối hợp task với nhân sự này không?', 'Đánh giá đồng nghiệp', 'RATING', NOW(), NOW()),
('Điểm tổng kết: Điểm số tổng kết chung bạn dành cho nhân sự này trong tháng (Thang 10).', 'Tổng kết', 'RATING', NOW(), NOW());
